# Generated by Django 4.0.2 on 2022-02-28 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
        ('imagestore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestore',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category'),
        ),
        migrations.AlterField(
            model_name='imagestore',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='imagestore.location'),
        ),
    ]
